"""Added date_naissance column

Revision ID: 3879f9b75534
Revises: 
Create Date: 2023-09-13 12:19:18.992152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3879f9b75534'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adherents', sa.Column('date_naissance', sa.Date(), nullable=False, comment="Date de naissance de l'adhérent"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adherents', 'date_naissance')
    # ### end Alembic commands ###
